### ISSUE TITLE
Helm Secret too large

### ISSUE THREAD

**Issue by simonostendorf** [community-tooling/charts#155]
Hello, 

i get the following error when installing the kube-prometheus-stack-crds.

`Error: create: failed to create: Secret "sh.helm.release.v1.kube-prometheus-stack-crds.v1" is invalid: data: Too long: must have at most 1048576 bytes`

Is there anything i can do against it? I found your discossion in https://github.com/community-tooling/charts/pull/64 but there was no "solution" for me.

I am using the following command to install the crds: `helm upgrade --install kube-prometheus-stack-crds community-tooling/kube-prometheus-stack-crds -n monitoring-system --create-namespace --version 55.5.2`

**Comment by morremeyer** [comment]
@simonostendorf I missed this issue, sorry for the delay.

_There is nothing we can do about this._

The root cause is that secrets have a maximum size of 1MiB, and that is not going to change in Kubernetes. 
helm writes all the templated resources into the `sh.helm.release.v1.…` secret. 

Once that secret would be > 1MiB, helm cannot create it anymore and therefore things like `helm diff` and `helm rollback` would not work anymore.

The only way to fix this is to not use helm to manage the charts. I personally use ArgoCD, which uses `helm template` to template helm charts, but does not use `helm install/upgrade` to deploy them.
